

"""

This Program used to as the user to Guess a Number between 0-100
after the user guess the number correctly will display a congrate + how many times
he / she tried

"""

import random as r 

def guessing_number(number_of_tries) :
    
    while True : 
        
        
        random_number = r.randint(0,10)     # the random number generated by the computer
        user_guessing_number = int(input('Enter Your Gussing Number between 0-100 ? ').strip()) 
        number_of_tries += 1    # each time user enter a number will increment by 1
        
        
        print()
        if (random_number == user_guessing_number) :
            
            print('Congrates, You Guessed the number')
            print('You have Tried ' + str(number_of_tries) + f' {"times" if number_of_tries > 1 else "time"}')
            print('Computer Guessing Number ' + str(random_number))
            print('Your Number  ' + str(user_guessing_number ))
            
             
        else :
            
            print('You Did Not Guessed the number')
            print('Computer Guessing Number ' + str(random_number))
            print( 'Your Number  ' + str(user_guessing_number) )
                
        keep_guessing = input('Do You Want To keep Gussing a Number? ').strip()
            
        if keep_guessing.lower() == 'no' or keep_guessing.lower() == 'n' :
            break

number_of_tries = 0

guessing_number(number_of_tries)









